language: java

dist: trusty

git:
  depth: false

cache:
  directories:
    - "${HOME}/.m2/"

install: true

script: mvn clean verify

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    draft: true
    on:
      tags: true
